language: node_js
node_js: "8"
cache: 
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

build:
  - yarn build

update_sitemap:
  - yarn prepare-sitemap

test:
  - yarn test-dist
