FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8

# Install the site
ADD ${site_root} /inetpub/wwwroot

# Add the startup script
ADD start.ps1 C:\shared\start.ps1
# Add the contrast config yaml file (optional)
ADD contrast_security.yaml c:\shared\contrast_security.yaml

# Setup Contrast .NET Agent and start the site
ENTRYPOINT [ "powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; /shared/start.ps1" ]
